### ISSUE TITLE
Find all JavaBean properties by type

### ISSUE THREAD

**Issue by ShishkinDmitriy** [hypergraphdb/hypergraphdb#125]
Hello,

I have 2 classes:
Class A and class P:
```java
@Getter
@Setter
@NoArgsConstructor
public class A {
	protected String name;
	protected P p;
}

@Getter
@Setter
@NoArgsConstructor
public class P {	
	protected String name;
}
```

Then I add it to the graph:
```java
A act = new A();
act.setP(new P());
graph.add(act);
```
And try to retrieve them:
```java
hg.findAll(graph, hg.type(A.class)) // will return instance of A.class
```
but:
```java
hg.findAll(graph, hg.type(P.class)) // will return nothing
```

As I can see, `JavaBeanBinding` register all bean properties into store, but how can I retrieve them?

Best regards,
Dmitriy

**Comment by bolerio** [comment]
Hi,

Bean properties are stored as part of the value and even though they are decomposed and serialized independently in storage, they are not atom per se. There is a special annotation to make a bean property be its own atom that you can search:

http://hypergraphdb.org/docs/javadoc/org/hypergraphdb/annotation/AtomReference.html <http://hypergraphdb.org/docs/javadoc/org/hypergraphdb/annotation/AtomReference.html>

Though the real documentation of how that behaves is here:

http://hypergraphdb.org/docs/javadoc/org/hypergraphdb/atom/HGAtomRef.html <http://hypergraphdb.org/docs/javadoc/org/hypergraphdb/atom/HGAtomRef.html>

And you can see examples in the unit test:

https://github.com/hypergraphdb/hypergraphdb/blob/master/testcore/test/java/hgtest/atomref/TestHGAtomRef.java <https://github.com/hypergraphdb/hypergraphdb/blob/master/testcore/test/java/hgtest/atomref/TestHGAtomRef.java>

HTH,
Boris

**Comment by ShishkinDmitriy** [comment]
Hi,

Thanks, it works)
The last small questuon. What if it is a collection or array, e.g. `private P[] p;`? I think it will be useful if annotation would have `boolean multiple()` attribute.

Best regards,
Dmitry

**Comment by bolerio** [comment]
I don’t know what happens if it’s an array. On top of my head, it should behave as any other object value  - you should get a single atom for the whole array, rather than a separate atom for each P. So good point on the ‘multiple’ option - do you mind entering a github issue?

**Comment by ShishkinDmitriy** [comment]
Submitted #126
