### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [hypergraphdb/hypergraphdb#131]
Could you please add an explicit `LICENSE` file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

GitHub's [Open Source guide](https://opensource.guide/legal/#are-public-github-projects-open-source) says:

> Making your GitHub project public is not the same as licensing your project. Public projects are covered by GitHub’s Terms of Service, which allows others to view and fork your project, but your work otherwise comes with no permissions.
>
> If you want others to use, distribute, modify, or contribute back to your project, you need to include an open source license. For example, someone cannot legally use any part of your GitHub project in their code, even if it’s public, unless you explicitly give them the right to do so.

Thanks!

**Comment by bolerio** [comment]
Thanks for pointing this out, @mbrukman! It must have been accidentally removed, or it could be an oversight when switching from Google Code to Github....

**Comment by mbrukman** [comment]
@bolerio — Thanks for fixing this! Google Code allowed specifying the license for the repo via an option in a drop-down, so unfortunately, many projects didn't have an explicit `LICENSE` file, and migrating the code did not migrate the metadata.

That said, the [license you just added](https://github.com/hypergraphdb/hypergraphdb/commit/3ff265d9f45a02336e9630e113bd012352d59688) is Apache 2.0, while the [original repo](https://code.google.com/archive/p/hypergraphdb/) specified LGPL. While you are the primary author and founder/CEO of Kobrix (so you or your company may already hold the copyright for the entirety of the code base), just wanted to point out the difference in licenses, in case you either wanted to keep the original license, or if if you don't hold the copyright to the entire code base, to check with the other author about the relicensing.

**Comment by bolerio** [comment]
@mbrukman Yes, I remember that feature of Google Code. The license change was completely intentional and I also remember adding that to the new repo or stating it somewhere, but I must be mistaken since I now realize that the readme.html file still refers to LGPL. Many thanks for bringing my attention to this!
